const ImagePath = {
    "Atlanta Hawks": require("../../assets/teamlogo/nba/Atlanta Hawks.gif"),
    "Boston Celtics": require("../../assets/teamlogo/nba/Boston Celtics.gif"),
    "Brooklyn Nets": require("../../assets/teamlogo/nba/Brooklyn Nets.gif"),
    "Charlotte Hornets": require("../../assets/teamlogo/nba/Charlotte Hornets.gif"),
    "Chicago Bulls": require("../../assets/teamlogo/nba/Chicago Bulls.gif"),
    "Cleveland Cavaliers": require("../../assets/teamlogo/nba/Cleveland Cavaliers.gif"),
    "Dallas Mavericks": require("../../assets/teamlogo/nba/Dallas Mavericks.gif"),
    "Denver Nuggets": require("../../assets/teamlogo/nba/Denver Nuggets.gif"),
    "Detroit Pistons": require("../../assets/teamlogo/nba/Detroit Pistons.gif"),
    "Golden State Warriors": require("../../assets/teamlogo/nba/Golden State Warriors.gif"),
    "Houston Rockets": require("../../assets/teamlogo/nba/Houston Rockets.gif"),
    "Indiana Pacers": require("../../assets/teamlogo/nba/Indiana Pacers.gif"),
    "Los Angeles Lakers": require("../../assets/teamlogo/nba/Los Angeles Lakers.gif"),
    "Memphis Grizzlies": require("../../assets/teamlogo/nba/Memphis Grizzlies.gif"),
    "Miami Heat": require("../../assets/teamlogo/nba/Miami Heat.gif"),
    "Milwaukee Bucks": require("../../assets/teamlogo/nba/Milwaukee Bucks.gif"),
    "Minnesota Timberwolves": require("../../assets/teamlogo/nba/Minnesota Timberwolves.gif"),
    "New Orleans Pelicans": require("../../assets/teamlogo/nba/New Orleans Pelicans.gif"),
    "New York Knicks": require("../../assets/teamlogo/nba/New York Knicks.gif"),
    "Oklahoma City Thunder": require("../../assets/teamlogo/nba/Oklahoma City Thunder.gif"),
    "Orlando Magic": require("../../assets/teamlogo/nba/Orlando Magic.gif"),
    "Philadelphia 76ers": require("../../assets/teamlogo/nba/Philadelphia 76ers.gif"),
    "Phoenix Suns": require("../../assets/teamlogo/nba/Phoenix Suns.gif"),
    "Portland Trail Blazers": require("../../assets/teamlogo/nba/Portland Trail Blazers.gif"),
    "Sacramento Kings": require("../../assets/teamlogo/nba/Sacramento Kings.gif"),
    "San Antonio Spurs": require("../../assets/teamlogo/nba/San Antonio Spurs.gif"),
    "Toronto Raptors": require("../../assets/teamlogo/nba/Toronto Raptors.gif"),
    "Utah Jazz": require("../../assets/teamlogo/nba/Utah Jazz.gif"),
    "Washington Wizards": require("../../assets/teamlogo/nba/Washington Wizards.gif"),
    "Denver Nuggets": require("../../assets/teamlogo/nba/Denver Nuggets.gif"),
    "LA Clippers" : require("../../assets/teamlogo/nba/LA Clippers.gif"),
    "western": require("../../assets/teamlogo/nba/western.png"),
    "eastern": require("../../assets/teamlogo/nba/eastern.png"),
    "defaultIcon": require("../../assets/icon.png"),
  };

  export default ImagePath;